name: Screener build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there"

  EnvironmentUpload:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir artifacts

      - name: Set base env variables
        run: |
          cat <<EOT >> artifacts/environment
          "BROWSERSLIST_IGNORE_OLD_DATA=true"
          "DEPLOYHOST='fluentuipr.z22.web.core.windows.net'"
          "BUILD_BUILDID=${{ github.run_id }}"
          "BUILD_SOURCEBRANCH=${{ github.ref }}"
          EOT

      - name: Set env variables if there is a PR
        run: |
          cat <<EOT >> artifacts/environment
          "SYSTEM_PULLREQUEST_TARGETBRANCH=${{ github.event.pull_request.base.ref }}"
          "SYSTEM_PULLREQUEST_SOURCEBRANCH=${{ github.event.pull_request.head.ref }}"
          "SYSTEM_PULLREQUEST_PULLREQUESTID=${{ github.event.pull_request.id }}"
          "SYSTEM_PULLREQUEST_SOURCECOMMITID=${{ github.event.pull_request.head.sha }}"
          "ISPR=true"
          "DEPLOYBASEPATH=pull/$PR_NUMBER"
          "DEPLOYURL=https://$DEPLOYHOST/pull/$PR_NUMBER"
          "BUILD_SOURCEBRANCHNAME='merge'"
          EOT
        env:
          PR_NUMBER: ${{ github.event.number }}
        if: ${{startsWith(github.ref, 'refs/pull/')}}

      - name: Set env variables if there is not a PR
        run: |
          cat <<EOT >> artifacts/environment
          "ISPR=false"
          "DEPLOYBASEPATH=heads/$SYSTEM_PULLREQUEST_TARGETBRANCH"
          "DEPLOYURL=https://$DEPLOYHOST/heads/$SYSTEM_PULLREQUEST_TARGETBRANCH"
          "BUILD_SOURCEBRANCHNAME=${{ github.ref_name }}"
          EOT
        if: ${{!startsWith(github.ref, 'refs/pull/')}}

      - name: Upload environment variables artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-artifact
          path: artifacts/environment

  ScreenerNorthStar:
    runs-on: 'ubuntu-latest'

    name: Screener @fluentui/react-northstar

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          "SHELLOPTS $SHELLOPTS" ;\

      - name: yarn
        run: ./yarn-ci.sh
        shell: bash

      - name: build FUI N* VR Test
        run: yarn workspace @fluentui/docs vr:build
        env:
          SCREENER_BUILD: 1

      - uses: actions/upload-artifact@v3
        with:
          name: northstar-artifact
          path: packages/fluentui/docs/dist

  Screener:
    runs-on: 'ubuntu-latest'

    name: Screener @fluentui/react

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          "SHELLOPTS $SHELLOPTS" ;\

      - name: yarn
        run: ./yarn-ci.sh
        shell: bash

      - name: build vr-tests storybook
        run: yarn workspace @fluentui/vr-tests screener:build

      - uses: actions/upload-artifact@v3
        with:
          name: screener-artifact
          path: apps/vr-tests/dist/storybook

  ScreenerVNext:
    runs-on: 'ubuntu-latest'

    name: Screener @fluentui/react-components

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.18.1

      - name: Log environment variables (Linux)
        if: runner.os == 'Linux'
        run: |
          printenv | sort ;\
          echo "SHELLOPTS $SHELLOPTS" ;\

      - name: yarn
        run: ./yarn-ci.sh
        shell: bash

      - name: build vr-tests-react-components storybook
        run: yarn workspace @fluentui/vr-tests-react-components screener:build

      - uses: actions/upload-artifact@v3
        with:
          name: vnext-artifact
          path: apps/vr-tests-react-components/dist/storybook
