on: pull_request
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there"

  ScreenerNorthStar:
    runs-on: 'ubuntu-latest'

    name: Screener @fluentui/react-northstar
    env:
        SKIPCOMPONENTGOVERNANCEDETECTION: true

        ConnectionString: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING}}

        BROWSERSLIST_IGNORE_OLD_DATA: true

        DEPLOYHOST: 'fluentuipr.z22.web.core.windows.net'

        SYSTEM_PULLREQUEST_TARGETBRANCH: ${{ github.event.pull_request.base.ref }}

        BUILD_SOURCEBRANCH: ${{ github.ref }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 14.18.1

    - name: Set env variables if there is a PR
      run: |
       echo "ISPR=true" >> $GITHUB_ENV
       echo "TARGETBRANCH=origin/$SYSTEM_PULLREQUEST_TARGETBRANCH" >> $GITHUB_ENV
       echo "DEPLOYBASEPATH=pull/$PR_NUMBER" >> $GITHUB_ENV
       echo "DEPLOYURL=https://$DEPLOYHOST/pull/$PR_NUMBER" >> $GITHUB_ENV
      env:
        PR_NUMBER: ${{ github.event.number }}
      if: ${{startsWith(github.ref, 'refs/pull/')}}

    - name: Set env variables if there is not a PR
      run: |
       echo "ISPR=false" >> $GITHUB_ENV
       echo "TARGETBRANCH=''" >> $GITHUB_ENV
       echo "DEPLOYBASEPATH=heads/$SYSTEM_PULLREQUEST_TARGETBRANCH" >> $GITHUB_ENV
       echo "DEPLOYURL=https://$DEPLOYHOST/heads/$SYSTEM_PULLREQUEST_TARGETBRANCH" >> $GITHUB_ENV
      if: ${{!startsWith(github.ref, 'refs/pull/')}}

    - name: Install yarn
      run: npm install --global yarn

    - name: Log environment variables (Linux)
      if: runner.os == 'Linux'
      run: |
        printenv | sort ;\
        echo "SHELLOPTS $SHELLOPTS" ;\

    - name: yarn
      run: ./yarn-ci.sh
      shell: bash

    - name: build FUI N* VR Test
      run: yarn workspace @fluentui/docs vr:build
      env:
        SCREENER_BUILD: 1

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -d '$web' -s 'packages/fluentui/docs/dist' --connection-string $ConnectionString

    - name: Start @fluentui/react-northstar VR Test
      run: yarn workspace @fluentui/docs vr:test
      env:
        SCREENER_ENDPOINT: ${{secrets.SCREENER_ENDPOINT}}
        SCREENER_PROXY_ENDPOINT: ${{secrets.SCREENER_PROXY_ENDPOINT}}
        SCREENER_API_KEY: ${{secrets.SCREENER_API_KEY}}

