on: pull_request

jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there"

  ScreenerNorthStar:
    runs-on: 'ubuntu-latest'

    name: Screener @fluentui/react-northstar
    env:
        $AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING}}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 14.18.1

    - name: Install yarn
      run: npm install --global yarn

    - name: Log environment variables (Linux)
      if: runner.os == 'Linux'
      run: |
        echo "SHELLOPTS $SHELLOPTS" ;\
        echo 'deployBasePath $deployBasePath' ;\
        echo 'deployUrl $deployUrl' ;\
        echo 'isPR $isPR' ;\
        echo 'targetBranch $targetBranch' \

    - name: yarn
      run: ./yarn-ci.sh
      shell: bash

    - name: build FUI N* VR Test
      run: yarn workspace @fluentui/docs vr:build
      env:
        SCREENER_BUILD: 1

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -d '$web' -s ''packages/fluentui/docs/dist' --connection-string '$AZURE_STORAGE_CONNECTION_STRING'


    - name: Start @fluentui/react-northstar VR Test
      run: yarn workspace @fluentui/docs vr:test
      env:
        SCREENER_ENDPOINT: $(screenerApiUri)
        SCREENER_PROXY_ENDPOINT: $(screenerProxyUri)
        SCREENER_API_KEY: $(screener.key)

